rta_search/config/routes.rb
# frozen_string_literal: true

# routes
Rails.application.routes.draw do
  root to: 'search#index'
  get 'search', to: 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rta_search/app/models/age.rb
# frozen_string_literal: true

# Age model
class Age < ApplicationRecord
  validates :range, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_search/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rta_search/app/models/country.rb
# frozen_string_literal: true

# Country Model
class Country < ApplicationRecord
  validates :name, :code, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_search/app/models/disease.rb
# frozen_string_literal: true

# Disease model
class Disease < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_search/app/models/month.rb
# frozen_string_literal: true

# Month Model
class Month < ApplicationRecord
  validates :name, :code, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_search/app/models/profile.rb
# frozen_string_literal: true

# Profile
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :year
  belongs_to :month
  belongs_to :country
  belongs_to :disease
  belongs_to :age

  validates :user, uniqueness: true, presence: true

  enum profile_type: %i[patient carer]
  enum gender: %i[male female]
end

rta_search/app/models/profile_datum.rb
# frozen_string_literal: true

# ProfileDatum Model
class ProfileDatum < ApplicationRecord

  def readonly?
    true
  end

  self.primary_key = :id

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name,
      concurrently: true,
      cascade: false)
  end
end

rta_search/app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  acts_as_paranoid
  enum status: %i[active suspended deleted]
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_one :profile, dependent: :destroy
end

rta_search/app/models/year.rb
# frozen_string_literal: true

# Year model
class Year < ApplicationRecord
  validates :year, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_search/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rta_search/app/controllers/search_controller.rb
# frozen_string_literal: true

# Search table
class SearchController < ApplicationController
  before_action :permit_params_for_profile, only: :index
  before_action :required_objects, only: :index

  def index
    ProfileDatum.refresh
    @query = ProfileDatum.ransack(params[:q])
    @profiles = @query.result(distinct: true)
  end

  private

  def permit_params_for_profile
    @params = params.permit(q: %i[user_name_cont email_eq status_eq gender_eq profile_type_eq age_range_eq country_code_eq disease_name_eq year_eq month_code_eq])
  end

  def required_objects
    @statuses = User.statuses.keys
    @genders = Profile.genders.keys
    @countries = Country.distinct.pluck(:code).compact.sort
    @years = Year.distinct.pluck(:year).compact.sort
    @months = Month.distinct.pluck(:code).compact.sort
    @ages = Age.distinct.pluck(:range).compact.sort
    @types = Profile.profile_types.keys
    @diseases = Disease.distinct.pluck(:name).compact.sort
  end
end

rta_search/app/helpers/application_helper.rb
module ApplicationHelper
end

rta_search/app/helpers/search_helper.rb
module SearchHelper
end

rta_search/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RtaSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rta_search/app/views/search/index.html.erb
<div class="jumbotron text-center">
  <h1>Raremark Technical Assignment Search</h1>
  <p>Search and Play!</p>
</div>
<div class="container">
  <%= search_form_for @query, url: search_path, method: :get do |f| %>
    <h2>Advanced Search</h2>
    <div class="row">
      <div class="col-sm-4">
        <%= f.label :email %>
        <%= f.search_field :email_eq, class: 'form-control' %>
      </div>

      <div class="col-sm-4">
        <%= f.label :name %>
        <%= f.search_field :user_name_cont, class: 'form-control' %>
      </div>

      <div class="col-sm-4">
        <%= f.label :status %>
        <%= f.select :status_eq, @statuses, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :country %>
        <%= f.select :country_code_eq, @countries, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :born_year %>
        <%= f.select :year_eq, @years, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :gender %>
        <%= f.select :gender_eq, @genders, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :born_month %>
        <%= f.select :month_code_eq, @months, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :age_range %>
        <%= f.select :age_range_eq, @ages, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :types %>
        <%= f.select :profile_type_eq, @types, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>

      <div class="col-sm-4">
        <%= f.label :disease %>
        <%= f.select :disease_name_eq, @diseases, { include_blank: false, prompt: true }, { class: 'select2 form-control' } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <br/>
        <%= f.submit 'Search', class: 'btn btn-primary js-search' %>
        <%= link_to 'clear', root_path, class: 'btn btn-primary js-clear' %>
      </div>
    </div>
  <% end %>
</div>

<% unless @profiles.nil? %>
  <% if @profiles.empty? %>
    <div class="container">
    <h2>No profiles found matching your query.</h2>
    </div>
  <% else %>
    <div id="profile-table" class="container">

      <h4>Search results (Users: <%= @profiles.count %>) </h4>

      <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Type</th>
          <th>Country</th>
          <th>Gender</th>
          <th>Disease</th>
        </tr>
        </thead>

        <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td><%= profile.id %></td>
            <td><%= profile.user_name %></td>
            <td><%= profile.email %></td>
            <td><%= profile.profile_type %></td>
            <td><%= profile.country_code %></td>
            <td><%= profile.gender %></td>
            <td><%= profile.disease_name %></td>
          </tr>
        <% end %>
        <tbody>
        </table>

      <div class="row">
        <div class="col-sm-4">
          <div class="chart">Gender</div>
          <%= pie_chart @profiles.group(:gender).count %>
        </div>

        <div class="col-sm-4">
          <div class="chart">Country</div>
          <%= pie_chart @profiles.group(:country_code).count %>
        </div>

        <div class="col-sm-4">
          <div class="chart">Type</div>
          <%= pie_chart @profiles.group(:profile_type).count %>
        </div>
      </div>
  <% end %>
  </div>
<% end %>