rta_admin/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :profiles
  resources :users
  resources :ages
  resources :countries
  resources :months
  resources :years
  resources :diseases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rta_admin/app/models/age.rb
# frozen_string_literal: true

# Age model
class Age < ApplicationRecord
  validates :range, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rta_admin/app/models/country.rb
# frozen_string_literal: true

# Country Model
class Country < ApplicationRecord
  validates :name, :code, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_admin/app/models/disease.rb
# frozen_string_literal: true

# Disease model
class Disease < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_admin/app/models/month.rb
# frozen_string_literal: true

# Month Model
class Month < ApplicationRecord
  validates :name, :code, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_admin/app/models/profile.rb
# frozen_string_literal: true

# Profile
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :year
  belongs_to :month
  belongs_to :country
  belongs_to :disease
  belongs_to :age

  validates :user, uniqueness: true, presence: true

  enum profile_type: %i[patient carer]
  enum gender: %i[male female]
end

rta_admin/app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  acts_as_paranoid
  enum status: %i[active suspended deleted]
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_one :profile, dependent: :destroy
end

rta_admin/app/models/year.rb
# frozen_string_literal: true

# Year model
class Year < ApplicationRecord
  validates :year, presence: true, uniqueness: true
  has_many :profiles, dependent: :destroy
end

rta_admin/app/controllers/ages_controller.rb
class AgesController < ApplicationController
  before_action :set_age, only: [:show, :edit, :update, :destroy]

  # GET /ages
  def index
    @ages = Age.all
  end

  # GET /ages/1
  def show
  end

  # GET /ages/new
  def new
    @age = Age.new
  end

  # GET /ages/1/edit
  def edit
  end

  # POST /ages
  def create
    @age = Age.new(age_params)

    if @age.save
      redirect_to @age, notice: 'Age was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ages/1
  def update
    if @age.update(age_params)
      redirect_to @age, notice: 'Age was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ages/1
  def destroy
    @age.destroy
    redirect_to ages_url, notice: 'Age was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_age
      @age = Age.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def age_params
      params.require(:age).permit(:range)
    end
end

rta_admin/app/controllers/diseases_controller.rb
# frozen_string_literal: true

# controller
class DiseasesController < ApplicationController
  before_action :set_disease, only: %i[show edit update destroy]

  # GET /diseases
  def index
    @diseases = Disease.all
  end

  # GET /diseases/1
  def show; end

  # GET /diseases/new
  def new
    @disease = Disease.new
  end

  # GET /diseases/1/edit
  def edit; end

  # POST /diseases
  def create
    @disease = Disease.new(disease_params)

    if @disease.save
      redirect_to @disease, notice: 'Disease was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /diseases/1
  def update
    if @disease.update(disease_params)
      redirect_to @disease, notice: 'Disease was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /diseases/1
  def destroy
    @disease.destroy
    redirect_to diseases_url, notice: 'Disease was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_disease
    @disease = Disease.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def disease_params
    params.require(:disease).permit(:name)
  end
end

rta_admin/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

rta_admin/app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :set_month, only: [:show, :edit, :update, :destroy]

  # GET /months
  def index
    @months = Month.all
  end

  # GET /months/1
  def show
  end

  # GET /months/new
  def new
    @month = Month.new
  end

  # GET /months/1/edit
  def edit
  end

  # POST /months
  def create
    @month = Month.new(month_params)

    if @month.save
      redirect_to @month, notice: 'Month was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /months/1
  def update
    if @month.update(month_params)
      redirect_to @month, notice: 'Month was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /months/1
  def destroy
    @month.destroy
    redirect_to months_url, notice: 'Month was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_month
      @month = Month.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def month_params
      params.require(:month).permit(:name, :code)
    end
end

rta_admin/app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :status,
                                 :deleted_at, :suspended_at)
  end
end

rta_admin/app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: [:show, :edit, :update, :destroy]

  # GET /years
  def index
    @years = Year.all
  end

  # GET /years/1
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years
  def create
    @year = Year.new(year_params)

    if @year.save
      redirect_to @year, notice: 'Year was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /years/1
  def update
    if @year.update(year_params)
      redirect_to @year, notice: 'Year was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /years/1
  def destroy
    @year.destroy
    redirect_to years_url, notice: 'Year was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def year_params
      params.require(:year).permit(:year)
    end
end

rta_admin/app/helpers/ages_helper.rb
module AgesHelper
end

rta_admin/app/helpers/application_helper.rb
module ApplicationHelper
end

rta_admin/app/helpers/countries_helper.rb
module CountriesHelper
end

rta_admin/app/helpers/diseases_helper.rb
module DiseasesHelper
end

rta_admin/app/helpers/home_helper.rb
module HomeHelper
end

rta_admin/app/helpers/months_helper.rb
module MonthsHelper
end

rta_admin/app/helpers/profiles_helper.rb
module ProfilesHelper
end

rta_admin/app/helpers/users_helper.rb
module UsersHelper
end

rta_admin/app/helpers/years_helper.rb
module YearsHelper
end

rta_admin/app/views/ages/_form.html.erb
<%= form_with(model: age, local: true) do |form| %>
  <% if age.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(age.errors.count, "error") %> prohibited this age from being saved:</h2>

      <ul>
      <% age.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :range %>
    <%= form.text_field :range %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rta_admin/app/views/ages/edit.html.erb
<h1>Editing Age</h1>

<%= render 'form', age: @age %>

<%= link_to 'Show', @age %> |
<%= link_to 'Back', ages_path %>

rta_admin/app/views/ages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ages</h1>

<table>
  <thead>
    <tr>
      <th>Range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ages.each do |age| %>
      <tr>
        <td><%= age.range %></td>
        <td><%= link_to 'Show', age %></td>
        <td><%= link_to 'Edit', edit_age_path(age) %></td>
        <td><%= link_to 'Destroy', age, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Age', new_age_path %>

rta_admin/app/views/ages/new.html.erb
<h1>New Age</h1>

<%= render 'form', age: @age %>

<%= link_to 'Back', ages_path %>

rta_admin/app/views/ages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Range:</strong>
  <%= @age.range %>
</p>

<%= link_to 'Edit', edit_age_path(@age) %> |
<%= link_to 'Back', ages_path %>

rta_admin/app/views/months/_form.html.erb
<%= form_with(model: month, local: true) do |form| %>
  <% if month.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(month.errors.count, "error") %> prohibited this month from being saved:</h2>

      <ul>
      <% month.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rta_admin/app/views/months/edit.html.erb
<h1>Editing Month</h1>

<%= render 'form', month: @month %>

<%= link_to 'Show', @month %> |
<%= link_to 'Back', months_path %>

rta_admin/app/views/months/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Months</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @months.each do |month| %>
      <tr>
        <td><%= month.name %></td>
        <td><%= month.code %></td>
        <td><%= link_to 'Show', month %></td>
        <td><%= link_to 'Edit', edit_month_path(month) %></td>
        <td><%= link_to 'Destroy', month, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Month', new_month_path %>

rta_admin/app/views/months/new.html.erb
<h1>New Month</h1>

<%= render 'form', month: @month %>

<%= link_to 'Back', months_path %>

rta_admin/app/views/months/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @month.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @month.code %>
</p>

<%= link_to 'Edit', edit_month_path(@month) %> |
<%= link_to 'Back', months_path %>

rta_admin/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, User.statuses.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rta_admin/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rta_admin/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>Deleted at</th>
      <th>Suspended at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.status %></td>
        <td><%= user.deleted_at %></td>
        <td><%= user.suspended_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

rta_admin/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

rta_admin/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @user.deleted_at %>
</p>

<p>
  <strong>Suspended at:</strong>
  <%= @user.suspended_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

rta_admin/app/views/years/_form.html.erb
<%= form_with(model: year, local: true) do |form| %>
  <% if year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
      <% year.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rta_admin/app/views/years/edit.html.erb
<h1>Editing Year</h1>

<%= render 'form', year: @year %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

rta_admin/app/views/years/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Years</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @years.each do |year| %>
      <tr>
        <td><%= year.year %></td>
        <td><%= link_to 'Show', year %></td>
        <td><%= link_to 'Edit', edit_year_path(year) %></td>
        <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year', new_year_path %>

rta_admin/app/views/years/new.html.erb
<h1>New Year</h1>

<%= render 'form', year: @year %>

<%= link_to 'Back', years_path %>

rta_admin/app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @year.year %>
</p>

<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>